export const AllData = [
  { value: Math.floor(Math.random() * 101), dataPointRadius: 133 }, // 0 dan 100 gacha tasodifiy qiymat
  { value: Math.floor(Math.random() * 101), dataPointRadius: 33 },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
]

export const HourData = [
  { value: 0 }, // 0 dan 100 gacha tasodifiy qiymat
  { value: 5 },
  { value: 20 },
  { value: 25 },
  { value: 28 },
  { value: 30 },
  { value: 40 },
  { value: 10 },
  { value: 10 },
  { value: 12 },
  { value: 13 },
  { value: 14 },
  { value: 20 },
  { value: 40 },
  { value: 40 },
  { value: 41 },
  { value: 43 },
  { value: 50 },
  { value: 48 },
  { value: 47 },
  { value: 30 },
  { value: 29 },
]

export const DayData = [
  { value: Math.floor(Math.random() * 101) }, // 0 dan 100 gacha tasodifiy qiymat
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
]

export const WeekData = [
  { value: Math.floor(Math.random() * 101) }, // 0 dan 100 gacha tasodifiy qiymat
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
]

export const MonthData = [
  { value: Math.floor(Math.random() * 101) }, // 0 dan 100 gacha tasodifiy qiymat
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
]

export const YearData = [
  { value: Math.floor(Math.random() * 101) }, // 0 dan 100 gacha tasodifiy qiymat
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
  { value: Math.floor(Math.random() * 101) },
]
